### ISSUE TITLE
AdvancedAchievements

### ISSUE THREAD

**Issue by huangwang1003** [imyvm/ZhuMeng-Minecraft-Server#1]
DistanceHorse:
  '10000':
    Message: '策马奔腾 10000 米'
    Name: '&c速度七十迈'
'100000':
    Message: '我们最终都要远行，最终都要跟稚嫩的自己告别'
    Name: '&c远行'
这两个Achievements有问题

**Comment by hanbi301** [comment]
骑马是100000米。没有10000米的成就。远航应该是66666米。

**Comment by imyvm** [comment]
成就无法达成么？看数据库骑马的成就有 3 个人完成；远行的成就有 2 个人完成，最近一个完成的日期是 7 月 18 号。

**Comment by huangwang1003** [comment]
100000米并没出现远行，66666米也没有远行

**Comment by imyvm** [comment]
查了下记录……步行距离是 2073348  骑马距离是
