### ISSUE TITLE
AdvancedAchievement

### ISSUE THREAD

**Issue by hanbi301** [imyvm/ZhuMeng-Minecraft-Server#4]
ItemDrops:
  #'100':
    #Message: '最讨厌乱扔东西的人惹~'
    #Name: '&c乱丢垃圾'

这个成就被撤销了。但是很多老玩家已经完成了，并且计算在成就总数里。对于新玩家来说很不公平。

**Comment by imyvm** [comment]
会重新启用这个成就的

**Comment by hanbi301** [comment]
大概什么时候会加回来？

**Comment by imyvm** [comment]
已加回

**Comment by hanbi301** [comment]
无法完成这个成就。

**Comment by imyvm** [comment]
ID 是？

**Comment by hanbi301** [comment]
Blackbone123
